---
- name: Include CentOS/RPM repos
  include_role: 
    name: repos-rpm-el7
  when: 
    - deployment_type == 'rpm'
    - ansible_distribution == 'CentOS'

- name: Iclude CentOS/docker repos
  include_role: 
    name: repos-docker-el7
  when: 
    - deployment_type == 'docker'
    - ansible_distribution == 'CentOS'
