---
all:
  vars:
    ansible_user: vagrant
    ansible_become: true
    docker_web_port: 8085
    deployment_type: docker
    database_host: localhost
    database_pass: upsilon
    database_user: upsilon
  children:
    drone:
      hosts:
        drone1:
          ansible_host: 192.168.66.192
        drone2:
          ansible_host: 192.168.66.226
        drone3:
          ansible_host: 192.168.66.216
    web:
      hosts:
        web1:
          ansible_host: 192.168.66.210
        web2:
          ansible_host: 192.168.66.173
        web3:
          ansible_host: 192.168.66.158
    amqp:
      hosts:
        rabbit:
          ansible_host: 192.168.66.215
    db:
      hosts:
        mysql:
          ansible_host: 192.168.66.175
    custodian:
      hosts:
        custodian1:
          ansible_host: 192.168.66.171
