---
- name: Yum install MariaDB server & client
  yum: name={{item}} state=present
  with_items: 
    - mariadb-server
    - mariadb

- name: Start and enable MariaDB service
  service: name=mariadb state=started enabled=yes
