---
- import_playbook: setup_docker.yml
  when: deployment_type == "docker"

- import_playbook: setup_rpm.yml
  when: deployment_type == "rpm"

- import_playbook: setup_allinone.yml
  when: "'allinone' in groups"
